### ISSUE TITLE
[Suggested]: Iloveremote.io

### ISSUE THREAD

**Issue by Imad-Moudouani** [georgemandis/remote-working-list#29]
### Title

I Love Remote - Worldwide Remote 💰 High-Paid Jobs Only

### URL

https://Iloveremote.io

### Feed URL

https://iloveremote.io/rss/jobs/new.rss

### Notes

new jobs RSS
https://iloveremote.io/rss/jobs/new.rss
Remote jobs RSS
https://iloveremote.io/rss/jobs/city/remote.rss
Jobs by city RSS 
https://iloveremote.io/rss/jobs/city/{city_code}.rss
Jobs by state RSS 
https://iloveremote.io/rss/jobs/state/{state_code}.rss
Jobs by country RSS 
https://iloveremote.io/rss/jobs/country/{country_code}.rss

**Comment by georgemandis** [comment]
Added! 

https://github.com/georgemandis/remote-working-list/blob/main/remote-working-resources.csv#L41
