### ISSUE TITLE
[Suggested]: Privacy-First Jobs

### ISSUE THREAD

**Issue by tagawa** [georgemandis/remote-working-list#30]
### Title

Privacy-First Jobs

### URL

https://privacyfirstjobs.com/jobs/remote

### Feed URL

https://privacyfirstjobs.com/jobs/feed

### Notes

Hi. This job board includes non-remote jobs as well, so I submitted the URL for the remote-only section.

**Comment by georgemandis** [comment]
Thanks @tagawa!

is there a way to setup the RSS feed to only filter for remote jobs? That's okay if not :)

**Comment by georgemandis** [comment]
I've gone ahead and merged it, but if you have an update on that feed I'll make the change.

Thanks!

**Comment by tagawa** [comment]
That's quick – thank you @georgemandis!
I don't have an RSS feed for only remote jobs I'm afraid, but I'll try to add that filter and will update here if/when I can do it.
